@echo off
echo Running tests for FC PR Tracker...

set GO111MODULE=on

echo.
echo Running unit tests...
go test -v ./pkg/...
go test -v ./internal/...
go test -v ./cmd/...

echo.
echo Running tests with coverage...
go test -v -coverprofile=coverage.out ./pkg/... ./internal/... ./cmd/...

echo.
echo Generating coverage report...
go tool cover -html=coverage.out -o coverage.html

echo.
echo Test execution completed.
echo Coverage report saved to coverage.html 